language: ruby
rvm:
  - 2.3.3

before_install:

install:
- gem install jekyll bundle
- bundle install

script:
  - jekyll build

after_success:
  - mkdir _site && mv README.md -t _site/
  - cd _site
  - git init
  - git config user.name "pusidun"
  - git config user.email "pusidun@hotmail.com"
  - git add --all .
  - git status
  - git commit -m "Travis-CI auto builder"
  - git push --force --quiet "https://${DEPLOY_TOKEN}@${GH_REF}" master:${P_BRANCH}
  - git push --force --quiet "https://${GE_USERNAME}:${GE_PASSWORD}@${GE_REF}" master:${P_BRANCH}

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
